language: c

sudo: required
dist: trusty
os:
 - linux
 - linux-ppc64le

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y autopoint libuv-dev libdevmapper-dev flex bison
 - ./bootstrap

install:
 - ./configure --with-twin-x11=no --with-twin-fbdev=no
 - make

script:
 - make check
